[[program]]
function = "karplus_strong_comb"
name = "KS PlasticPipe"
[program.sound.values]
polarity = "negative"
excitation = "pink"
[program.effects]
chain = ["eq2", "reverb"]
[program.effects.configs.reverb.mapping]
wet_amount = 1
length = 2
[program.effects.configs.reverb.values]
room_size = 7.0
damping   = 0.4
length    = 2.5
wet_amount = 0.6