#[[program]]
#function = "chorused_dirty_guitar"
#name = "chorused dirty guitar"
#
#[[program]]
#function = "plastic_pipe"
#name = "plastic pipe"
[[program]]
function = "Square_saw_soft"
name = "soft square+saw"
tuning = "just intonation"
[program.effects]
chain = ["eq2", "reverb"]
[program.effects.reverb]
# Construction parameters (never modulated)
room_size = 8.8
damping   = 0.5
length    = 4.2
# CC‑mappable parameter: wet_amount
wet_amount = 0.9
[program.effects.eq2]
lowcut = 0.0
highcut = 1.0


[[program]]
function = "Square_saw_soft"
name = "soft square+saw2"
tuning = "just intonation"
[program.effects]
chain = ["reverb"]
[program.effects.reverb]
# Construction parameters (never modulated)
room_size = 8.8
damping   = 0.5
length    = 4.2