[[program]]
function = "chorused_dirty_guitar"
name = "chorused dirty guitar"

[[program]]
function = "plastic_pipe"
name = "plastic pipe"

[[program]]
function = "Square_saw_soft"
name = "soft square+saw"
tuning = "just intonation"