[[program]]
function = "super_osc"
name = "super tri"
[program.effects]

[program.effects.configs.reverb.values]
# Construction parameters (never modulated)
room_size = 6.0
damping   = 0.5
length    = 2.2
# CC‑mappable parameter: wet_amount
wet_amount = 0.5
[program.effects.configs.eq2.values]
lowcut = 0.0
highcut = 1.0