[global]
# Arturia keylab essential 49
# FX: Encoders
# Sound: Faders
# Using DAW mode - as it allows for screen feedback
sound_cc_mapping = [
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
]
fx_cc_mapping = [
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
]
left_right_buttons = [
    25,
    26,
]
